// ============================================
// מצפן קריירה - DATA.JS
// נתוני שוק ההון הישראלי 2024-2025
// ============================================

// כל תפקידי שוק ההון הישראלי
const ALL_ROLES = [
  // ייעוץ השקעות ופנסיה
  "יועץ השקעות",
  "יועץ פנסיוני",
  "יועץ פנסיוני בכיר",
  "יועץ השקעות בכיר",
  "מנהל תיקי השקעות",
  "מנהל תיקים - Private Banking",
  "מנהל עושר (Wealth Manager)",

  // פרייבט בנקינג
  "יועץ Private Banking",
  "מנהל יחסי לקוחות - פרייבט",
  "בנקאי פרטי",

  // ניהול השקעות מוסדי
  "מנהל השקעות מוסדי",
  "מנהל קרן נאמנות",
  "מנהל קרן פנסיה",
  "מנהל קרן גידור",
  "מנהל תיקים מוסדי",
  "Chief Investment Officer (CIO)",
  "מנהל אגף השקעות",
  "מנהל השקעות - ביטוח",
  "מנהל תיקים - גמל והשתלמות",

  // אנליזה ומחקר
  "אנליסט מניות",
  "אנליסט אשראי",
  "אנליסט מאקרו",
  "אנליסט כלכלי",
  "אנליסט פיננסי",
  "אנליסט קרנות",
  "אנליסט סיכונים",
  "אנליסט נתונים פיננסי",
  "כלכלן ראשי",
  "כלכלן",
  "חוקר שוק הון",

  // סיכונים ורגולציה
  "מנהל סיכוני שוק",
  "מנהל סיכוני אשראי",
  "מנהל סיכונים (Chief Risk Officer)",
  "קצין ציות ורגולציה",
  "ממונה ציות",
  "מנהל ביקורת פנימית",
  "אנליסט ציות",
  "מנהל רגולציה",

  // פינטק ודיגיטל
  "מנהל מוצר - פינטק",
  "מנהל מוצר - השקעות דיגיטליות",
  "יועץ WealthTech",
  "מנהל פרויקטים פיננסיים",
  "מפתח אלגוריתמים פיננסיים",
  "מנהל Robo-Advisory",

  // מסחר ושוק ראשוני
  "סוחר (Trader) - מניות",
  "סוחר אגרות חוב",
  "סוחר מטבע חוץ",
  "סוחר נגזרים",
  "מנהל מסחר (Head of Trading)",
  "עושה שוק (Market Maker)",
  "סוחר קנייה (Buy-Side Trader)",
  "סוחר מכירה (Sell-Side Trader)",

  // חיתום ובנקאות השקעות
  "בנקאי השקעות",
  "אנליסט - בנקאות השקעות",
  "מנהל - חיתום ניירות ערך",
  "מנהל הנפקות (IPO)",
  "מנהל M&A",
  "אנליסט M&A",

  // ביטוח ואקטואריה
  "אקטואר",
  "אקטואר בכיר",
  "מנהל הסדרי ביטוח",
  "חוקר ביטוח",
  "מנהל השקעות - ביטוח חיים",
  "מנהל מוצרי ביטוח",

  // עצמאי ויעוץ
  "יועץ פיננסי עצמאי",
  "מתכנן פיננסי (CFP)",
  "יועץ עסקי פיננסי",
  "יועץ חיצוני - שוק הון",
  "מנהל השקעות עצמאי",

  // ניהול ובכירים
  "מנהל אגף ייעוץ",
  "מנהל אזורי - ייעוץ",
  "ראש מחלקת מחקר",
  "ראש מחלקת סיכונים",
  "מנהל כספים (CFO)",
  "סמנכ\"ל השקעות",
  "סמנכ\"ל פיננסים",

  // תפקידי תמיכה ומבצע
  "Back Office - ניירות ערך",
  "Middle Office - השקעות",
  "מנהל פיקדונות",
  "יועץ מט\"ח",
  "מנהל נוסטרו",
];

// מאגר תפקידים עם נתוני שכר מדויקים (ישראל 2024-2025, ברוטו)
const CAREER_DATA = {

  roles: [
    {
      id: "investment-advisor",
      title: "יועץ השקעות",
      description: "ייעוץ ללקוחות בנק על תיקי ניירות ערך, קרנות נאמנות ואגרות חוב. בנק מתאים לניסיון של עד 10 שנים לפני מעבר לתפקיד בכיר.",
      salaryRange: "18,000 - 26,000 ₪",
      salaryMin: 18000, salaryMax: 26000,
      stressLevel: "בינוני-גבוה",
      stressScore: 3.5,
      workLifeBalance: "בינוני",
      balanceScore: 3,
      flexibility: "נמוכה",
      growthPotential: 3,
      matchRoles: ["יועץ השקעות","יועץ השקעות בכיר","יועץ פנסיוני"],
      matchOrg: ["bank"],
      matchNature: ["client","mix"],
      pBoost: { p_salary:0.8, p_stability:1.0, p_balance:0.7, p_growth:0.7, p_lowstress:0.6, p_flexibility:0.5 }
    },
    {
      id: "senior-investment-advisor",
      title: "יועץ השקעות בכיר",
      description: "ניהול תיקי לקוחות VIP בבנק, אוטונומיה גבוהה יותר, ליווי לקוחות מורכבים עם נכסים גדולים. פוטנציאל עמלות משמעותי.",
      salaryRange: "24,000 - 38,000 ₪",
      salaryMin: 24000, salaryMax: 38000,
      stressLevel: "בינוני-גבוה",
      stressScore: 3.5,
      workLifeBalance: "בינוני",
      balanceScore: 3,
      flexibility: "נמוכה",
      growthPotential: 3,
      matchRoles: ["יועץ השקעות בכיר","יועץ השקעות","מנהל תיקי השקעות","יועץ Private Banking"],
      matchOrg: ["bank","investment_house"],
      matchNature: ["client","management","mix"],
      pBoost: { p_salary:0.95, p_stability:1.0, p_growth:0.8, p_balance:0.7, p_lowstress:0.65 }
    },
    {
      id: "private-banking",
      title: "יועץ Private Banking",
      description: "ליווי לקוחות עשירים (HNW) עם נכסים של מעל 2M ₪. שירות אינטגרטיבי: השקעות, מיסוי, פנסיה, הלוואות. יוקרה ושכר גבוה.",
      salaryRange: "30,000 - 55,000 ₪ + בונוסים",
      salaryMin: 30000, salaryMax: 55000,
      stressLevel: "בינוני-גבוה",
      stressScore: 3.5,
      workLifeBalance: "בינוני",
      balanceScore: 3,
      flexibility: "נמוכה-בינונית",
      growthPotential: 4,
      matchRoles: ["יועץ Private Banking","מנהל תיקים - Private Banking","יועץ השקעות בכיר","מנהל עושר (Wealth Manager)"],
      matchOrg: ["bank","investment_house"],
      matchNature: ["client","mix"],
      pBoost: { p_salary:1.1, p_prestige:1.1, p_growth:0.9, p_balance:0.65, p_lowstress:0.6, p_stability:1.0 }
    },
    {
      id: "portfolio-manager",
      title: "מנהל תיקי השקעות",
      description: "ניהול עצמאי של תיקים בבית השקעות עם לקוחות מעל 500K ₪. קבלת החלטות השקעה, ביצועים נמדדים מול בנצ'מרק.",
      salaryRange: "30,000 - 60,000 ₪",
      salaryMin: 30000, salaryMax: 60000,
      stressLevel: "גבוה",
      stressScore: 4,
      workLifeBalance: "נמוך-בינוני",
      balanceScore: 2.5,
      flexibility: "נמוכה",
      growthPotential: 4,
      matchRoles: ["מנהל תיקי השקעות","מנהל תיקים - Private Banking","מנהל תיקים מוסדי"],
      matchOrg: ["investment_house","bank"],
      matchNature: ["analytical","client","management"],
      pBoost: { p_salary:1.1, p_growth:1.0, p_prestige:1.0, p_balance:0.5, p_lowstress:0.4, p_stability:0.8, p_flexibility:0.5 }
    },
    {
      id: "institutional-investment-manager",
      title: "מנהל השקעות מוסדי",
      description: "ניהול נכסי קרנות פנסיה, ביטוח וגמל. תיקים של מאות מיליונים. יוקרה מקסימלית, אחריות גדולה, שכר הכי גבוה בענף.",
      salaryRange: "45,000 - 90,000 ₪",
      salaryMin: 45000, salaryMax: 90000,
      stressLevel: "גבוה מאוד",
      stressScore: 4.5,
      workLifeBalance: "נמוך",
      balanceScore: 2,
      flexibility: "נמוכה",
      growthPotential: 4,
      matchRoles: ["מנהל השקעות מוסדי","מנהל קרן נאמנות","מנהל קרן פנסיה","Chief Investment Officer (CIO)","מנהל אגף השקעות"],
      matchOrg: ["investment_house","insurance","bank"],
      matchNature: ["analytical","management"],
      pBoost: { p_salary:1.3, p_prestige:1.2, p_growth:0.9, p_balance:0.3, p_lowstress:0.2, p_stability:0.7, p_flexibility:0.3 }
    },
    {
      id: "equity-analyst",
      title: "אנליסט מניות / מחקר",
      description: "ניתוח מעמיק של חברות ציבוריות, כתיבת דוחות מחקר, המלצות השקעה. עבודה אינטנסיבית אבל מרתקת. שכר עולה עם ניסיון.",
      salaryRange: "22,000 - 45,000 ₪",
      salaryMin: 22000, salaryMax: 45000,
      stressLevel: "גבוה",
      stressScore: 4,
      workLifeBalance: "נמוך-בינוני",
      balanceScore: 2.5,
      flexibility: "נמוכה",
      growthPotential: 4,
      matchRoles: ["אנליסט מניות","אנליסט פיננסי","אנליסט כלכלי","אנליסט מאקרו","חוקר שוק הון","ראש מחלקת מחקר"],
      matchOrg: ["investment_house","bank","fintech"],
      matchNature: ["analytical"],
      pBoost: { p_salary:0.9, p_growth:1.2, p_balance:0.4, p_lowstress:0.3, p_stability:0.7, p_flexibility:0.5 }
    },
    {
      id: "risk-manager",
      title: "מנהל סיכונים",
      description: "ניתוח סיכוני שוק, אשראי ותפעול. תפקיד רגולטורי חשוב עם ביקוש גבוה. שעות סבירות, יציבות גבוהה, פחות לחץ ממסחר.",
      salaryRange: "25,000 - 50,000 ₪",
      salaryMin: 25000, salaryMax: 50000,
      stressLevel: "בינוני",
      stressScore: 3,
      workLifeBalance: "בינוני-טוב",
      balanceScore: 3.5,
      flexibility: "בינונית",
      growthPotential: 3,
      matchRoles: ["מנהל סיכוני שוק","מנהל סיכוני אשראי","מנהל סיכונים (Chief Risk Officer)","אנליסט סיכונים"],
      matchOrg: ["bank","insurance","investment_house"],
      matchNature: ["analytical","management"],
      pBoost: { p_stability:1.2, p_balance:1.0, p_lowstress:1.0, p_salary:0.9, p_growth:0.8, p_flexibility:0.8 }
    },
    {
      id: "compliance",
      title: "קצין ציות ורגולציה",
      description: "אחריות על עמידה בחוקי רשות ניירות ערך, כללי בנק ישראל, FATCA ו-MiFID. שעות ידועות מראש, לחץ נמוך, ביקוש גובר.",
      salaryRange: "22,000 - 42,000 ₪",
      salaryMin: 22000, salaryMax: 42000,
      stressLevel: "נמוך-בינוני",
      stressScore: 2.5,
      workLifeBalance: "טוב",
      balanceScore: 4,
      flexibility: "בינונית-גבוהה",
      growthPotential: 3,
      matchRoles: ["קצין ציות ורגולציה","ממונה ציות","אנליסט ציות","מנהל רגולציה","מנהל ביקורת פנימית"],
      matchOrg: ["bank","insurance","investment_house"],
      matchNature: ["analytical","mix"],
      pBoost: { p_stability:1.2, p_balance:1.2, p_lowstress:1.3, p_salary:0.6, p_growth:0.7, p_flexibility:1.0 }
    },
    {
      id: "fintech-product",
      title: "מנהל מוצר - פינטק / השקעות דיגיטליות",
      description: "הגדרת מוצרים פיננסיים דיגיטליים, ממשקי רובו-אדוויזורי, פלטפורמות מסחר. שוק חם, היברידי, שכר גבוה, צמיחה מהירה.",
      salaryRange: "28,000 - 58,000 ₪",
      salaryMin: 28000, salaryMax: 58000,
      stressLevel: "בינוני",
      stressScore: 3,
      workLifeBalance: "טוב",
      balanceScore: 3.5,
      flexibility: "גבוהה",
      growthPotential: 5,
      matchRoles: ["מנהל מוצר - פינטק","מנהל מוצר - השקעות דיגיטליות","יועץ WealthTech","מנהל Robo-Advisory"],
      matchOrg: ["fintech","bank","investment_house"],
      matchNature: ["product","analytical","mix"],
      pBoost: { p_growth:1.3, p_flexibility:1.2, p_salary:1.0, p_balance:1.0, p_stability:0.5, p_lowstress:0.9 }
    },
    {
      id: "data-analyst",
      title: "אנליסט נתונים פיננסי",
      description: "ניתוח נתוני שוק ולקוחות עם Python, SQL, Tableau. ביקוש גבוה, עבודה היברידית, פחות לחץ, שכר עולה. מתאים למי שאוהב data.",
      salaryRange: "20,000 - 40,000 ₪",
      salaryMin: 20000, salaryMax: 40000,
      stressLevel: "נמוך-בינוני",
      stressScore: 2.5,
      workLifeBalance: "טוב",
      balanceScore: 4,
      flexibility: "גבוהה",
      growthPotential: 4,
      matchRoles: ["אנליסט נתונים פיננסי","אנליסט פיננסי"],
      matchOrg: ["bank","fintech","insurance","investment_house"],
      matchNature: ["analytical","product"],
      pBoost: { p_balance:1.1, p_flexibility:1.2, p_growth:1.0, p_lowstress:1.1, p_salary:0.7, p_stability:0.9 }
    },
    {
      id: "trader",
      title: "סוחר (Trader) - נוסטרו / פרופ",
      description: "מסחר עצמאי בניירות ערך, מטבע חוץ ונגזרים. עבודה אינטנסיבית בשעות השוק. שכר בסיס נמוך יחסית אבל בונוס גבוה מאוד.",
      salaryRange: "20,000 - 80,000 ₪ (בסיס + בונוס)",
      salaryMin: 20000, salaryMax: 80000,
      stressLevel: "גבוה מאוד",
      stressScore: 5,
      workLifeBalance: "נמוך",
      balanceScore: 2,
      flexibility: "נמוכה",
      growthPotential: 3,
      matchRoles: ["סוחר (Trader) - מניות","סוחר אגרות חוב","סוחר מטבע חוץ","סוחר נגזרים","מנהל מסחר (Head of Trading)","עושה שוק (Market Maker)"],
      matchOrg: ["bank","investment_house"],
      matchNature: ["analytical"],
      pBoost: { p_salary:1.2, p_growth:0.8, p_balance:0.3, p_lowstress:0.2, p_stability:0.5, p_flexibility:0.3 }
    },
    {
      id: "investment-banking",
      title: "בנקאי השקעות / M&A",
      description: "ליווי עסקאות הנפקה, מיזוגים ורכישות. שעות ארוכות מאוד, לחץ גבוה, שכר גבוה מאוד, למידה מהירה. בדרך כלל עד גיל 35.",
      salaryRange: "30,000 - 75,000 ₪ + בונוס",
      salaryMin: 30000, salaryMax: 75000,
      stressLevel: "גבוה מאוד",
      stressScore: 5,
      workLifeBalance: "נמוך מאוד",
      balanceScore: 1.5,
      flexibility: "נמוכה מאוד",
      growthPotential: 5,
      matchRoles: ["בנקאי השקעות","אנליסט - בנקאות השקעות","מנהל M&A","אנליסט M&A","מנהל הנפקות (IPO)"],
      matchOrg: ["bank","investment_house"],
      matchNature: ["analytical","management"],
      pBoost: { p_salary:1.3, p_growth:1.3, p_prestige:1.2, p_balance:0.2, p_lowstress:0.1, p_stability:0.5, p_flexibility:0.2 }
    },
    {
      id: "actuary",
      title: "אקטואר",
      description: "מודלים סטטיסטיים לתמחור ביטוח, פנסיה וסיכונים. מקצוע נדיר עם שכר גבוה ויציבות גבוהה. דרישות: מבחני CT/CM.",
      salaryRange: "28,000 - 65,000 ₪",
      salaryMin: 28000, salaryMax: 65000,
      stressLevel: "בינוני",
      stressScore: 3,
      workLifeBalance: "טוב",
      balanceScore: 4,
      flexibility: "בינונית",
      growthPotential: 4,
      matchRoles: ["אקטואר","אקטואר בכיר","מנהל השקעות - ביטוח חיים"],
      matchOrg: ["insurance","bank"],
      matchNature: ["analytical"],
      pBoost: { p_stability:1.3, p_salary:1.1, p_balance:1.1, p_growth:1.0, p_lowstress:1.0, p_flexibility:0.9 }
    },
    {
      id: "independent-financial-advisor",
      title: "יועץ / מתכנן פיננסי עצמאי",
      description: "עבודה עצמאית מול לקוחות פרטיים ועסקיים. הכנסה ללא תקרה תלוית לקוחות, גמישות מלאה. מתאים אחרי ניסיון בבנק.",
      salaryRange: "15,000 - 80,000 ₪ (תלוי לקוחות)",
      salaryMin: 15000, salaryMax: 80000,
      stressLevel: "בינוני",
      stressScore: 3,
      workLifeBalance: "גבוה",
      balanceScore: 4.5,
      flexibility: "גבוהה מאוד",
      growthPotential: 4,
      matchRoles: ["יועץ פיננסי עצמאי","מתכנן פיננסי (CFP)","יועץ חיצוני - שוק הון","מנהל השקעות עצמאי"],
      matchOrg: ["independent"],
      matchNature: ["client","mix"],
      pBoost: { p_flexibility:1.4, p_balance:1.2, p_growth:1.0, p_salary:0.8, p_stability:0.4, p_lowstress:0.9 }
    },
    {
      id: "pension-advisor",
      title: "יועץ פנסיוני",
      description: "ייעוץ בפנסיה, ביטוחי חיים ואובדן כושר עבודה. תפקיד בביקוש גבוה עם לחץ בינוני. אפשרות לעצמאות בהמשך.",
      salaryRange: "16,000 - 28,000 ₪",
      salaryMin: 16000, salaryMax: 28000,
      stressLevel: "בינוני",
      stressScore: 3,
      workLifeBalance: "בינוני-טוב",
      balanceScore: 3.5,
      flexibility: "בינונית",
      growthPotential: 3,
      matchRoles: ["יועץ פנסיוני","יועץ פנסיוני בכיר","מנהל מוצרי ביטוח"],
      matchOrg: ["bank","insurance","independent"],
      matchNature: ["client","mix"],
      pBoost: { p_stability:1.0, p_balance:1.0, p_lowstress:1.0, p_salary:0.6, p_growth:0.7, p_flexibility:0.9 }
    }
  ],

  companies: [
    {
      id: "excellence",
      name: "אקסלנס נשואה",
      type: "בית השקעות",
      typeCategory: "investment_house",
      description: "אחד מבתי ההשקעות הגדולים בישראל. ניהול תיקים, קרנות, מסחר. תרבות תחרותית, שכר טוב, מוניטין חזק.",
      salaryRange: "25,000 - 65,000 ₪",
      salaryMin: 25000, salaryMax: 65000,
      workModel: "היברידי חלקי",
      culture: "מקצועית ותחרותית",
      size: "בינונית-גדולה",
      matchOrg: ["investment_house","no_pref"],
      matchNature: ["analytical","management","client"],
      matchRoles: ["מנהל תיקי השקעות","אנליסט מניות","מנהל השקעות מוסדי"],
      pBoost: { p_salary:1.1, p_growth:1.0, p_prestige:0.9, p_stability:0.8, p_balance:0.7 }
    },
    {
      id: "altshuler",
      name: "אלטשולר שחם",
      type: "בית השקעות",
      typeCategory: "investment_house",
      description: "בית השקעות צומח עם מוניטין חזק. ניהול גמל, פנסיה, קרנות ותיקים. ידועים בביצועים טובים ואווירת עבודה טובה.",
      salaryRange: "27,000 - 70,000 ₪",
      salaryMin: 27000, salaryMax: 70000,
      workModel: "היברידי",
      culture: "דינמית עם תשתית חזקה",
      size: "בינונית-גדולה",
      matchOrg: ["investment_house","no_pref"],
      matchNature: ["analytical","management"],
      matchRoles: ["מנהל תיקי השקעות","אנליסט מניות","מנהל השקעות מוסדי"],
      pBoost: { p_salary:1.1, p_growth:1.1, p_prestige:1.0, p_balance:0.9, p_stability:0.8 }
    },
    {
      id: "psagot",
      name: "פסגות השקעות",
      type: "בית השקעות",
      typeCategory: "investment_house",
      description: "ניהול תיקים, קרנות נאמנות ומחקר. אווירת בוטיק עם משאבים של חברה גדולה. מוניטין טוב בשוק.",
      salaryRange: "25,000 - 60,000 ₪",
      salaryMin: 25000, salaryMax: 60000,
      workModel: "משרד בעיקר",
      culture: "מקצועית ומוכוונת ביצועים",
      size: "בינונית",
      matchOrg: ["investment_house","no_pref"],
      matchNature: ["analytical","management","client"],
      matchRoles: ["מנהל תיקי השקעות","אנליסט מניות"],
      pBoost: { p_salary:1.0, p_growth:0.9, p_prestige:1.0, p_balance:0.7, p_stability:0.9 }
    },
    {
      id: "harel",
      name: "הראל ביטוח והשקעות",
      type: "קבוצה פיננסית",
      typeCategory: "insurance",
      description: "קבוצה גדולה עם ביטוח, פנסיה והשקעות. יציבות גבוהה, תנאים טובים, שעות סבירות. אפשרויות מעבר בין מחלקות.",
      salaryRange: "22,000 - 55,000 ₪",
      salaryMin: 22000, salaryMax: 55000,
      workModel: "היברידי",
      culture: "יציבה ומקצועית",
      size: "גדולה",
      matchOrg: ["insurance","no_pref"],
      matchNature: ["analytical","management","client"],
      matchRoles: ["אקטואר","מנהל סיכונים","קצין ציות ורגולציה","יועץ פנסיוני"],
      pBoost: { p_stability:1.2, p_balance:1.0, p_salary:0.8, p_growth:0.8, p_lowstress:1.0 }
    },
    {
      id: "migdal",
      name: "מגדל ביטוח",
      type: "חברת ביטוח",
      typeCategory: "insurance",
      description: "חברת הביטוח הגדולה ביותר בישראל. ניהול נכסים, פנסיה, ביטוח חיים. שעות טובות, שכר מתאים, אווירה יציבה.",
      salaryRange: "20,000 - 52,000 ₪",
      salaryMin: 20000, salaryMax: 52000,
      workModel: "היברידי",
      culture: "יציבה ומוסדית",
      size: "גדולה",
      matchOrg: ["insurance","no_pref"],
      matchNature: ["analytical","management"],
      matchRoles: ["אקטואר","מנהל סיכונים","מנהל השקעות - ביטוח"],
      pBoost: { p_stability:1.2, p_lowstress:1.0, p_balance:1.1, p_salary:0.75, p_growth:0.75 }
    },
    {
      id: "leumi-private",
      name: "בנק לאומי - Private Banking",
      type: "בנק - פרייבט",
      typeCategory: "bank",
      description: "מחלקת ה-Private Banking של לאומי עם לקוחות HNW. יוקרה מקצועית גבוהה, שכר טוב, תנאי העסקה מעולים.",
      salaryRange: "28,000 - 55,000 ₪",
      salaryMin: 28000, salaryMax: 55000,
      workModel: "משרד בעיקר",
      culture: "יוקרתית ומקצועית",
      size: "גדולה",
      matchOrg: ["bank","no_pref"],
      matchNature: ["client","mix"],
      matchRoles: ["יועץ Private Banking","יועץ השקעות בכיר"],
      pBoost: { p_prestige:1.2, p_stability:1.1, p_salary:0.9, p_balance:0.75, p_growth:0.8, p_lowstress:0.7 }
    },
    {
      id: "discount-investment",
      name: "דיסקונט - ניהול תיקים",
      type: "בנק",
      typeCategory: "bank",
      description: "אחד הבנקים עם מחלקת ניהול תיקים פעילה. תנאי בנק יציבים, שכר בינוני-טוב, פחות לחץ מבית השקעות עצמאי.",
      salaryRange: "22,000 - 48,000 ₪",
      salaryMin: 22000, salaryMax: 48000,
      workModel: "מעורב",
      culture: "מסורתית-מקצועית",
      size: "גדולה",
      matchOrg: ["bank","no_pref"],
      matchNature: ["client","management","mix"],
      matchRoles: ["יועץ השקעות","יועץ Private Banking","מנהל תיקי השקעות"],
      pBoost: { p_stability:1.2, p_prestige:0.9, p_salary:0.8, p_balance:0.85, p_lowstress:0.8 }
    },
    {
      id: "one-zero",
      name: "One Zero / פינטק דיגיטלי",
      type: "בנק דיגיטלי / פינטק",
      typeCategory: "fintech",
      description: "בנקים ופינטקים דיגיטליים ישראליים. עבודה היברידית, אינובציה, אופציות, אווירת הייטק. ידע פיננסי + תפיסה טכנולוגית.",
      salaryRange: "28,000 - 65,000 ₪ + אופציות",
      salaryMin: 28000, salaryMax: 65000,
      workModel: "היברידי / מרחוק",
      culture: "דינמית ואינובטיבית",
      size: "קטנה-בינונית",
      matchOrg: ["fintech","no_pref"],
      matchNature: ["product","analytical","mix"],
      matchRoles: ["מנהל מוצר - פינטק","אנליסט נתונים פיננסי","יועץ WealthTech"],
      pBoost: { p_growth:1.3, p_flexibility:1.3, p_salary:1.0, p_balance:1.0, p_stability:0.4, p_lowstress:0.9 }
    },
    {
      id: "more",
      name: "מור בית השקעות",
      type: "בית השקעות",
      typeCategory: "investment_house",
      description: "בית השקעות ישראלי עם גדילה מהירה. ניהול קרנות, גמל, פנסיה ותיקים. מוניטין עולה, תרבות צעירה ומקצועית.",
      salaryRange: "25,000 - 62,000 ₪",
      salaryMin: 25000, salaryMax: 62000,
      workModel: "היברידי",
      culture: "צעירה ומקצועית",
      size: "בינונית",
      matchOrg: ["investment_house","no_pref"],
      matchNature: ["analytical","management"],
      matchRoles: ["מנהל תיקי השקעות","אנליסט מניות","מנהל השקעות מוסדי"],
      pBoost: { p_salary:1.0, p_growth:1.2, p_prestige:0.85, p_balance:0.9, p_stability:0.75 }
    },
    {
      id: "ilan-shmerler",
      name: "בוטיק השקעות / קרן גידור",
      type: "בוטיק / קרן גידור",
      typeCategory: "investment_house",
      description: "בתי השקעות בוטיק וקרנות גידור ישראליות (דיאמונד, ריאל, אורבך). אוטונומיה גבוהה, בונוסים גדולים, צוות קטן.",
      salaryRange: "35,000 - 100,000 ₪ (בסיס + בונוס)",
      salaryMin: 35000, salaryMax: 100000,
      workModel: "משרד בעיקר",
      culture: "עצמאית ותחרותית מאוד",
      size: "קטנה",
      matchOrg: ["investment_house","independent","no_pref"],
      matchNature: ["analytical","management"],
      matchRoles: ["מנהל תיקי השקעות","סוחר (Trader) - מניות","מנהל השקעות מוסדי","מנהל קרן גידור"],
      pBoost: { p_salary:1.4, p_growth:1.2, p_prestige:1.1, p_balance:0.4, p_lowstress:0.3, p_stability:0.4, p_flexibility:0.4 }
    }
  ]
};
